"""Hardcoded weekly focus and per-lesson goal/task text.

This content must be returned to the user verbatim, never paraphrased or
regenerated by the LLM, so it lives here as plain data and is served through
a code-level override in coach/agent.py (see detect_lesson_goal_request,
detect_week_focus_request, detect_generic_weekly_query).
"""

from typing import Dict

LESSON_GOALS: Dict[int, str] = {
    1: (
        "Go to the \"Goals\" page and choose a \"Suggested Goal\" or create your own physical "
        "activity goal for the week, an aerobic, strength, or balance activity that feels "
        "realistic and enjoyable for you."
    ),
    2: (
        "Check in on your goal from this week. Go to the \"Goals\" page to mark it complete or "
        "set a new goal before your next lesson."
    ),
    3: (
        "Go to the \"Goals\" page and lock in a \"Suggested Goal\" or set a custom goal, keeping "
        "the recommendation of moderate-to-vigorous physical activity per week in mind."
    ),
}

WEEK_FOCUS: Dict[int, str] = {}

LESSON_TO_WEEK: Dict[int, int] = {1: 1, 2: 1, 3: 2}

OUT_OF_RANGE_MESSAGE = (
    "That’s outside of the information available to me as part of the Education group in this study. I can talk about lessons 1-3 and the science behind them, including the reflective side of the M-PAC framework (why to be active, how it feels, and what makes it possible to start)."
)

CLARIFYING_QUESTION = "Which lesson (or week) number are you currently on?"


def ambiguous_number_question(num: int) -> str:
    """Ask whether a bare number refers to a lesson or a week."""
    return f"Did you mean lesson {num} or week {num}?"
